import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import gv100h.spec_qa.retrieval.real_corpus_retriever as real_corpus_retriever
from gv100h.spec_qa.contracts.governed_chunk import GovernedChunk
from gv100h.spec_qa.retrieval.real_corpus_retriever import evaluate_retrieval



def _chunk(
    *,
    source_id: str,
    section: str,
    page: str,
    content: str,
    kind: str = "paragraph",
    index: int = 0,
) -> GovernedChunk:
    return GovernedChunk.build(
        source_id=source_id,
        document=(
            "USB 3.2 Specification"
            if source_id == "usb32"
            else "USB 2.0 Specification"
        ),
        revision="Rev 1.1" if source_id == "usb32" else "2.0",
        section=section,
        page_or_anchor=page,
        authority_level="authoritative",
        chunk_kind=kind,
        content=content,
        index=index,
    )


@pytest.fixture()
def chunks():
    return [
        _chunk(
            source_id="usb32",
            section="6.9.3",
            page="p.135",
            content="6.9.3 Warm Reset",
            kind="heading_only",
            index=0,
        ),
        _chunk(
            source_id="usb32",
            section="6.9.3",
            page="p.135",
            content=(
                "A Warm Reset is generated by a downstream port and detected "
                "at any link state except SS.Disabled."
            ),
            index=1,
        ),
        _chunk(
            source_id="usb32",
            section="6.9.1",
            page="p.131",
            content="Table 6-30. LFPS Transmitter Timing for SuperSpeed Designs",
            index=2,
        ),
        _chunk(
            source_id="usb32",
            section="6.9.1",
            page="p.131",
            content="tBurst | tRepeat | Logic value\n80 us | 100 us | Warm Reset",
            kind="table",
            index=3,
        ),
        _chunk(
            source_id="usb32",
            section="10.3",
            page="p.414",
            content="PORT_POWER feature selector value is 8.",
            index=4,
        ),
        _chunk(
            source_id="usb20_se",
            section="7.1",
            page="p.220",
            content="USB 2.0 hub suspend and resume state behavior.",
            index=5,
        ),
    ]



def test_query_returns_ranked_governed_chunks_with_provenance(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    hits = retriever.query("6.9.3 Warm Reset", top_k=3)

    assert hits
    assert any(
        hit.chunk.source_id == "usb32"
        and hit.chunk.section == "6.9.3"
        and hit.chunk.page_or_anchor == "p.135"
        for hit in hits
    )
    assert hits[0].score > 0
    assert "warm" in hits[0].matched_terms
    assert hits[0].chunk.to_citation().evidence_id == hits[0].chunk.chunk_id



def test_query_uses_section_caption_context_to_find_table_chunk(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    hits = retriever.query("Table 6-30 LFPS Transmitter Timing", top_k=5)

    table_hits = [hit for hit in hits if hit.chunk.chunk_kind == "table"]
    assert table_hits
    assert table_hits[0].chunk.source_id == "usb32"
    assert table_hits[0].chunk.section == "6.9.1"
    assert table_hits[0].chunk.page_or_anchor == "p.131"



def test_query_can_limit_results_to_allowed_source_ids(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    hits = retriever.query(
        "hub suspend resume state",
        top_k=5,
        allowed_source_ids={"usb20_se"},
    )

    assert hits
    assert all(hit.chunk.source_id == "usb20_se" for hit in hits)



def test_empty_source_filter_returns_no_results(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    assert retriever.query("Warm Reset", allowed_source_ids=set()) == []



def test_query_empty_or_unknown_terms_returns_no_results(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    assert retriever.query("   ") == []
    assert retriever.query("xyzzy_nonexistent") == []
    assert retriever.query("Warm Reset", top_k=0) == []



def test_retrieval_is_deterministic_for_same_chunk_sequence(chunks):
    first = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    second = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)

    first_records = [hit.as_record() for hit in first.query("Warm Reset", top_k=5)]
    second_records = [hit.as_record() for hit in second.query("Warm Reset", top_k=5)]

    assert first.corpus_sha256 == second.corpus_sha256
    assert first_records == second_records



def test_duplicate_chunk_ids_are_rejected(chunks):
    with pytest.raises(ValueError, match="unique chunk_id"):
        real_corpus_retriever.GovernedChunkBM25Retriever([chunks[0], chunks[0]])



def test_from_corpus_lock_loads_chunks_through_existing_ingestion_loader(
    chunks, monkeypatch, tmp_path
):
    calls = {}

    def fake_load(source_ids, corpus_lock, *, raw_root):
        calls["source_ids"] = tuple(source_ids)
        calls["corpus_lock"] = corpus_lock
        calls["raw_root"] = raw_root
        return chunks

    monkeypatch.setattr(real_corpus_retriever, "load_accepted_chunks", fake_load)
    lock = {"sources": {"usb32": {"layer": "official_raw"}}}

    retriever = real_corpus_retriever.GovernedChunkBM25Retriever.from_corpus_lock(
        lock,
        source_ids=("usb32",),
        raw_root=tmp_path,
    )

    assert len(retriever) == len(chunks)
    assert calls == {
        "source_ids": ("usb32",),
        "corpus_lock": lock,
        "raw_root": tmp_path,
    }


@pytest.mark.parametrize(
    "kwargs, message",
    [
        ({"k1": 0}, "k1 must be greater than zero"),
        ({"b": -0.1}, "b must be between zero and one"),
        ({"b": 1.1}, "b must be between zero and one"),
    ],
)
def test_invalid_bm25_parameters_are_rejected(chunks, kwargs, message):
    with pytest.raises(ValueError, match=message):
        real_corpus_retriever.GovernedChunkBM25Retriever(chunks, **kwargs)



def test_retrieval_package_exports_real_corpus_retriever():
    from gv100h.spec_qa.retrieval import (
        GovernedChunkBM25Retriever,
        GovernedChunkRetrievalHit,
    )

    assert GovernedChunkBM25Retriever is real_corpus_retriever.GovernedChunkBM25Retriever
    assert GovernedChunkRetrievalHit is real_corpus_retriever.GovernedChunkRetrievalHit


def test_evaluate_retrieval_reports_recall_and_mrr_without_content(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    cases = [
        {
            "id": "warm-reset",
            "query": "6.9.3 Warm Reset",
            "allowed_source_ids": ["usb32"],
            "target": {
                "source_id": "usb32",
                "section": "6.9.3",
                "page_or_anchor": "p.135",
            },
        },
        {
            "id": "usb2-suspend",
            "query": "hub suspend resume state",
            "allowed_source_ids": ["usb20_se"],
            "target": {"source_id": "usb20_se", "chapter": "7"},
        },
    ]

    summary = evaluate_retrieval(retriever, cases, top_k=3)

    assert summary["queries_evaluated"] == 2
    assert summary["recall@1"] == 100.0
    assert summary["recall@3"] == 100.0
    assert summary["recall@5"] == 100.0
    assert summary["mrr"] == 1.0
    assert [row["target_rank"] for row in summary["cases"]] == [1, 1]
    assert all(
        "content" not in hit
        for row in summary["cases"]
        for hit in row["top_hits"]
    )


def test_selector_targets_distinguish_same_metadata_chunks():
    power = _chunk(
        source_id="usb32",
        section="10.16.2.10",
        page="p.483",
        content="PORT_POWER feature selector value is 8.",
        index=10,
    )
    link_state = _chunk(
        source_id="usb32",
        section="10.16.2.10",
        page="p.483",
        content="PORT_LINK_STATE feature selector value is 5.",
        index=11,
    )
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(
        [power, link_state]
    )
    cases = [
        {
            "id": "power",
            "query": "PORT_POWER feature selector value",
            "allowed_source_ids": ["usb32"],
            "target": {"chunk_id": power.chunk_id},
        },
        {
            "id": "link-state",
            "query": "PORT_LINK_STATE feature selector value",
            "allowed_source_ids": ["usb32"],
            "target": {"chunk_id": link_state.chunk_id},
        },
    ]

    summary = evaluate_retrieval(retriever, cases, top_k=1)

    assert [row["target_rank"] for row in summary["cases"]] == [1, 1]
    assert [
        row["top_hits"][0]["chunk_id"] for row in summary["cases"]
    ] == [power.chunk_id, link_state.chunk_id]


def test_evaluate_retrieval_respects_requested_top_k_output(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    cases = [
        {
            "id": "warm-reset",
            "query": "Warm Reset",
            "allowed_source_ids": ["usb32"],
            "target": {"section": "6.9.3"},
        }
    ]

    summary = evaluate_retrieval(retriever, cases, top_k=1)

    assert summary["cases"][0]["hit_count"] == 3
    assert len(summary["cases"][0]["top_hits"]) == 1


def test_evaluate_retrieval_keeps_missed_target_visible(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    cases = [
        {
            "id": "missing-target",
            "query": "Warm Reset",
            "allowed_source_ids": ["usb32"],
            "target": {"source_id": "usb32", "section": "99.1"},
        }
    ]

    summary = evaluate_retrieval(retriever, cases)

    assert summary["recall@1"] == 0.0
    assert summary["recall@3"] == 0.0
    assert summary["recall@5"] == 0.0
    assert summary["mrr"] == 0.0
    assert summary["cases"][0]["target_rank"] is None


def test_evaluate_retrieval_rejects_malformed_cases(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    with pytest.raises(ValueError, match="id, query, and target"):
        evaluate_retrieval(retriever, [{"id": "missing-target"}])


@pytest.mark.parametrize(
    "target",
    [{}, {"secton": "6.9.3"}, {"page": "p.135"}],
)
def test_evaluate_retrieval_rejects_underspecified_or_unknown_targets(chunks, target):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    case = {"id": "bad-target", "query": "Warm Reset", "target": target}
    with pytest.raises(ValueError, match="recognized constraint|unknown constraints"):
        evaluate_retrieval(retriever, [case])


def test_hit_score_keeps_full_precision_but_serializes_rounded_score(chunks):
    retriever = real_corpus_retriever.GovernedChunkBM25Retriever(chunks)
    hit = retriever.query("Warm Reset", top_k=1)[0]

    assert hit.score != round(hit.score, 6) or hit.score == 0
    assert hit.as_record()["score"] == round(hit.score, 6)
